# Generated by Django 3.2.22 on 2023-11-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='amount',
            field=models.FloatField(choices=[('Pound (£)', '£'), ('Naira (N)', 'N')], default='Pound (£)', max_length=10, verbose_name='unit'),
        ),
    ]
