# Generated by Django 3.2.22 on 2023-11-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xchange', '0003_auto_20231104_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='currency',
            field=models.CharField(choices=[('GBP', 'GBP'), ('NGN', 'NGN')], default='GBP', max_length=10),
        ),
    ]
