# Generated by Django 3.2.22 on 2023-10-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BMIRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='code')),
                ('unit', models.CharField(choices=[('PERCENTAGE', 'percentage'), ('CURRENCY', 'currency')], default='PERCENTAGE', max_length=10, verbose_name='unit')),
                ('usage', models.CharField(choices=[('ONE_TIME', 'one-time only'), ('INFINITE', 'infinite')], max_length=8, verbose_name='usage')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
                ('valid_until', models.DateTimeField(blank=True, db_index=True, default=None, null=True, verbose_name='valid until')),
                ('promoted', models.BooleanField(default=False, help_text='show in topbar', verbose_name='promoted')),
                ('add_to_cart', models.BooleanField(default=False, help_text='automatically', verbose_name='add to cart')),
                ('max_items', models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='max items in cart')),
            ],
        ),
    ]
