# Generated by Django 3.2.22 on 2023-10-22 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmi_app', '0002_auto_20231022_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmirecord',
            name='add_to_cart',
        ),
        migrations.RemoveField(
            model_name='bmirecord',
            name='code',
        ),
        migrations.RemoveField(
            model_name='bmirecord',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bmirecord',
            name='max_items',
        ),
        migrations.RemoveField(
            model_name='bmirecord',
            name='promoted',
        ),
        migrations.RemoveField(
            model_name='bmirecord',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='bmirecord',
            name='usage',
        ),
        migrations.RemoveField(
            model_name='bmirecord',
            name='valid_until',
        ),
    ]
